# Generated by Django 5.0.3 on 2024-05-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.client')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.review')),
            ],
            options={
                'unique_together': {('review', 'client')},
            },
        ),
    ]
