# Generated by Django 5.0.4 on 2024-04-17 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0007_employee_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='static/media/profile_default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='desconhecido', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='static/media/profile_default.png', upload_to=''),
        ),
    ]
