# Generated by Django 5.0.4 on 2024-04-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0011_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selected_times', models.JSONField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(default='static/media/profile_default.png', upload_to='')),
                ('banner', models.ImageField(default='static/media/profile_default.png', upload_to='')),
                ('is_approved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.client')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.services'),
        ),
        migrations.DeleteModel(
            name='Servicos',
        ),
    ]
