# Generated by Django 5.0.4 on 2024-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0012_services_alter_appointment_service_delete_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='menuItems',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
