# Generated by Django 5.0.4 on 2024-05-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0013_services_menuitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='menuItems',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.client'),
        ),
    ]
