# Generated by Django 5.0.4 on 2024-05-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_scheduler_api', '0014_remove_appointment_employee_appointment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_scheduler_api.client'),
        ),
    ]
